apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s98kg6m9m-go
  janus-idp.io/tekton: s98kg6m9m-go
  backstage.io/kubernetes-id: s98kg6m9m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s98kg6m9m-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
